
name: First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: Ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome!"
      - name: Print Good bye
        run: echo "Bye!!!"
  secondjob:
    needs: [firstjob]
    runs-on: Ubuntu-latest
    steps:
      - name: check version
        run: cat /etc/lsb-release
  thirdjob:
    needs: [firstjob]
    uses: ./.github/workflows/second.yml
  fourthjob:
    runs-on:  Ubuntu-latest
    steps: 
      - name : update 
        run: apt-get update

