name: Running on Container
on: [push]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    container: ghcr.io/easybuilders/centos-7.9:latest
    steps:
      - name: display
        run: cat /etc/centos-release
