name: Matrix Demo
on: workflow_call
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest,windows-latest] 
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Install Node JS
        run: cat /etc/lsb-release
